apiVersion: v1
kind: Pod
metadata:
  name: demo-k8s-swd-pod
spec:
  containers:
    - name: demo-container-k8s-swd
      image: k8s_swd:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
          protocol: TCP